kind: pipeline
name: build-image

steps:
- name: build
  image: plugins/docker
  settings:
    repo: registry.datadynamic.io/moop/hello-world
    registry: registry.datadynamic.io
    auto_tag: true
    username:
      from_secret: repo-username
    password:
      from_secret: repo-password
