kind: pipeline
name: helloworld-ci

steps:

- name: build-image
  image: plugins/docker
  settings:
    repo: registry.datadynamic.io/moop/hello-world
    registry: registry.datadynamic.io
    tags: "${DRONE_TAG}"
    # tags: "${DRONE_COMMIT}"
    username:
      from_secret: repo-username
    password:
      from_secret: repo-password
  when:
    event:
    - tag

- name: k8s-deploy
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_server: https://192.168.0.31:6443
    kubernetes_token: 
      from_secret: kube-token
    namespace: drone-test
    deployment: drone-test
    repo: registry.datadynamic.io/moop/hello-world
    container: drone-test
    tag: "${DRONE_TAG}"
  when:
    event:
    - tag
